In [2]:
import numpy as np

## #Creating array

In [3]:
arr1 = np.array([1,2,3,4,5], dtype=int)
print(arr1)

[1 2 3 4 5]


In [5]:
arr2 = np.zeros(10,dtype = int)
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr2 = arr2.astype(np.float64)

In [15]:
arr3 = np.arange(0,20,3)
print(arr3)

[ 0  3  6  9 12 15 18]


In [16]:
arr4 = np.linspace(0,10,20)
print(arr4)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


#### -Multidimentional Array

In [58]:
arr5 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr6 = np.array([[10],[20],[30]])

In [4]:
# Slicing on 2d array
arr = np.arange(1,10)
arr_2d = arr.reshape((3,3))
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(arr_2d[2,2])
print(arr_2d[:,1])

9
[2 5 8]


In [59]:
arr5[::-1,::-1]

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [60]:
b = arr5[0,:]
b[0] = 100

In [6]:
#sorting
s = np.random.random(9) * 10
print(s)
arr = s.astype(np.int64)
print(arr)

[9.69573453 3.57106534 9.74893966 1.08784223 4.61113785 9.25310517
 2.82200957 7.65755401 1.77233296]
[9 3 9 1 4 9 2 7 1]


In [7]:
arr_sort = np.sort(arr)
print(arr_sort)

[1 1 2 3 4 7 9 9 9]


In [10]:
# 2D sorting
arr_2d = arr.reshape(3,3)
print(arr_2d)

[[9 3 9]
 [1 4 9]
 [2 7 1]]


In [65]:
arr = np.array([10,20,30,40], dtype=int)
arr.resize((3,3))

In [11]:
row_sort = np.sort(arr_2d, axis = 1)
print(row_sort)
col_sort = np.sort(arr_2d, axis = 0)
print(col_sort)

[[3 9 9]
 [1 4 9]
 [1 2 7]]
[[1 3 1]
 [2 4 9]
 [9 7 9]]


In [ ]:
#reshape and resize

In [66]:
arr

array([[10, 20, 30],
       [40,  0,  0],
       [ 0,  0,  0]])

In [98]:
arr = arr.reshape((9))

In [68]:
arr

array([[10, 20, 30],
       [40,  0,  0],
       [ 0,  0,  0]])

In [ ]:
#masking / filtering 

In [79]:
arr7 = np.random.randint(0,100,30)
arr8 = np.arange(100)

In [74]:
arr7[arr7 > 50].size

21

In [89]:
mask = (arr7 > 50) & (arr7 < 75)
arr7[mask]

array([59, 60, 52, 61, 72, 70], dtype=int32)

In [94]:
np.where(mask,True,False)
# np.where(condition) : returns the indices where the condition is true
# np.where(condition, x, y) : returns x if condition true and y if false
"""
if(condition) {
    x
} else {
    y
} 
"""

array([False, False, False,  True, False, False,  True, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False])

In [95]:
np.sum(arr5,axis = 1)

array([105,  15,  24,  33])

In [97]:
np.mean(arr5)

np.float64(14.75)

In [123]:
np.insert(arr5,0,[0,0,0,0],axis = 1)

array([[  0, 100,   2,   3],
       [  0,   4,   5,   6],
       [  0,   7,   8,   9],
       [  0,  10,  11,  12]])

In [48]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr3,arr4,arr5 = np.array_split(arr, 3)
arr3

array([1, 2])

In [36]:
arr = np.arange(1,10,0.5)

In [4]:
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [16]:
arr[::-1]

array([9.5, 9. , 8.5, 8. , 7.5, 7. , 6.5, 6. , 5.5, 5. , 4.5, 4. , 3.5,
       3. , 2.5, 2. , 1.5, 1. ])

In [37]:
arr = arr.astype(np.int64)

In [19]:
arr1,arr2,arr3 = np.array_split(arr,3)

In [21]:
arr1

array([1, 1, 2, 2, 3, 3])

In [24]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
np.array_split(arr,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [41]:
arr1 = np.arange(1,5)

In [42]:
arr1

array([1, 2, 3, 4])

In [45]:
arr1.resize((4,2), refcheck = False)

In [46]:
arr1

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0]])

In [ ]:
# adding row and coloum in matrix
a = np.array([[1,2], [3,4]])
# vstack : vertical stack ( to add a new row)
# hstack : horizontal stack ( to add a new coloum)
new_row = np.array([[5,6]])
a = np.vstack((a,new_row))
print(a)
new_col = np.array([[7],[8],[9]])
a = np.hstack((a,new_col))
print("\n", a)